//services/vehicle/proto/vehicle.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: vehicle.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================= Enums =================
type VehicleStatus int32

const (
	VehicleStatus_STATUS_UNSPECIFIED VehicleStatus = 0
	VehicleStatus_ACTIVE             VehicleStatus = 1
	VehicleStatus_MAINTENANCE        VehicleStatus = 2
	VehicleStatus_RETIRED            VehicleStatus = 3
	VehicleStatus_ASSIGNED           VehicleStatus = 4
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "MAINTENANCE",
		3: "RETIRED",
		4: "ASSIGNED",
	}
	VehicleStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"MAINTENANCE":        2,
		"RETIRED":            3,
		"ASSIGNED":           4,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vehicle_proto_enumTypes[0].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_vehicle_proto_enumTypes[0]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

type FuelType int32

const (
	FuelType_FUEL_UNSPECIFIED FuelType = 0
	FuelType_PETROL           FuelType = 1
	FuelType_DIESEL           FuelType = 2
	FuelType_ELECTRIC         FuelType = 3
	FuelType_HYBRID           FuelType = 4
)

// Enum value maps for FuelType.
var (
	FuelType_name = map[int32]string{
		0: "FUEL_UNSPECIFIED",
		1: "PETROL",
		2: "DIESEL",
		3: "ELECTRIC",
		4: "HYBRID",
	}
	FuelType_value = map[string]int32{
		"FUEL_UNSPECIFIED": 0,
		"PETROL":           1,
		"DIESEL":           2,
		"ELECTRIC":         3,
		"HYBRID":           4,
	}
)

func (x FuelType) Enum() *FuelType {
	p := new(FuelType)
	*p = x
	return p
}

func (x FuelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FuelType) Descriptor() protoreflect.EnumDescriptor {
	return file_vehicle_proto_enumTypes[1].Descriptor()
}

func (FuelType) Type() protoreflect.EnumType {
	return &file_vehicle_proto_enumTypes[1]
}

func (x FuelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FuelType.Descriptor instead.
func (FuelType) EnumDescriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{1}
}

// ================= Vehicle Type Messages =================
type VehicleType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleType) Reset() {
	*x = VehicleType{}
	mi := &file_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleType) ProtoMessage() {}

func (x *VehicleType) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleType.ProtoReflect.Descriptor instead.
func (*VehicleType) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VehicleType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateVehicleTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleTypeRequest) Reset() {
	*x = CreateVehicleTypeRequest{}
	mi := &file_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleTypeRequest) ProtoMessage() {}

func (x *CreateVehicleTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleTypeRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVehicleTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateVehicleTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   *VehicleType           `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleTypeResponse) Reset() {
	*x = CreateVehicleTypeResponse{}
	mi := &file_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleTypeResponse) ProtoMessage() {}

func (x *CreateVehicleTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleTypeResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVehicleTypeResponse) GetVehicleType() *VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return nil
}

type ListVehicleTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehicleTypesRequest) Reset() {
	*x = ListVehicleTypesRequest{}
	mi := &file_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehicleTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehicleTypesRequest) ProtoMessage() {}

func (x *ListVehicleTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehicleTypesRequest.ProtoReflect.Descriptor instead.
func (*ListVehicleTypesRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *ListVehicleTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVehicleTypesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVehicleTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleTypes  []*VehicleType         `protobuf:"bytes,1,rep,name=vehicle_types,json=vehicleTypes,proto3" json:"vehicle_types,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehicleTypesResponse) Reset() {
	*x = ListVehicleTypesResponse{}
	mi := &file_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehicleTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehicleTypesResponse) ProtoMessage() {}

func (x *ListVehicleTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehicleTypesResponse.ProtoReflect.Descriptor instead.
func (*ListVehicleTypesResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *ListVehicleTypesResponse) GetVehicleTypes() []*VehicleType {
	if x != nil {
		return x.VehicleTypes
	}
	return nil
}

func (x *ListVehicleTypesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ================= Core Vehicle Messages =================
type Vehicle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // external_id
	VehicleTypeId    string                 `protobuf:"bytes,2,opt,name=vehicle_type_id,json=vehicleTypeId,proto3" json:"vehicle_type_id,omitempty"`       // reference to vehicle_type
	VehicleTypeName  string                 `protobuf:"bytes,3,opt,name=vehicle_type_name,json=vehicleTypeName,proto3" json:"vehicle_type_name,omitempty"` // for convenience
	LicensePlate     string                 `protobuf:"bytes,4,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Make             string                 `protobuf:"bytes,5,opt,name=make,proto3" json:"make,omitempty"`
	Model            string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Year             int32                  `protobuf:"varint,7,opt,name=year,proto3" json:"year,omitempty"`
	Color            string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	SeatingCapacity  int32                  `protobuf:"varint,9,opt,name=seating_capacity,json=seatingCapacity,proto3" json:"seating_capacity,omitempty"`
	FuelType         FuelType               `protobuf:"varint,10,opt,name=fuel_type,json=fuelType,proto3,enum=vehicle.FuelType" json:"fuel_type,omitempty"`
	EngineNumber     string                 `protobuf:"bytes,11,opt,name=engine_number,json=engineNumber,proto3" json:"engine_number,omitempty"`
	ChassisNumber    string                 `protobuf:"bytes,12,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	InsuranceExpiry  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=insurance_expiry,json=insuranceExpiry,proto3" json:"insurance_expiry,omitempty"`
	Status           VehicleStatus          `protobuf:"varint,15,opt,name=status,proto3,enum=vehicle.VehicleStatus" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetVehicleTypeId() string {
	if x != nil {
		return x.VehicleTypeId
	}
	return ""
}

func (x *Vehicle) GetVehicleTypeName() string {
	if x != nil {
		return x.VehicleTypeName
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetSeatingCapacity() int32 {
	if x != nil {
		return x.SeatingCapacity
	}
	return 0
}

func (x *Vehicle) GetFuelType() FuelType {
	if x != nil {
		return x.FuelType
	}
	return FuelType_FUEL_UNSPECIFIED
}

func (x *Vehicle) GetEngineNumber() string {
	if x != nil {
		return x.EngineNumber
	}
	return ""
}

func (x *Vehicle) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *Vehicle) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *Vehicle) GetInsuranceExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.InsuranceExpiry
	}
	return nil
}

func (x *Vehicle) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_STATUS_UNSPECIFIED
}

func (x *Vehicle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Vehicle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *VehicleInput          `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVehicleRequest) GetVehicle() *VehicleInput {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type VehicleInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VehicleTypeId    string                 `protobuf:"bytes,1,opt,name=vehicle_type_id,json=vehicleTypeId,proto3" json:"vehicle_type_id,omitempty"`
	LicensePlate     string                 `protobuf:"bytes,2,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Make             string                 `protobuf:"bytes,3,opt,name=make,proto3" json:"make,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year             int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Color            string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	SeatingCapacity  int32                  `protobuf:"varint,7,opt,name=seating_capacity,json=seatingCapacity,proto3" json:"seating_capacity,omitempty"`
	FuelType         FuelType               `protobuf:"varint,8,opt,name=fuel_type,json=fuelType,proto3,enum=vehicle.FuelType" json:"fuel_type,omitempty"`
	EngineNumber     string                 `protobuf:"bytes,9,opt,name=engine_number,json=engineNumber,proto3" json:"engine_number,omitempty"`
	ChassisNumber    string                 `protobuf:"bytes,10,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	InsuranceExpiry  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=insurance_expiry,json=insuranceExpiry,proto3" json:"insurance_expiry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleInput) Reset() {
	*x = VehicleInput{}
	mi := &file_vehicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInput) ProtoMessage() {}

func (x *VehicleInput) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInput.ProtoReflect.Descriptor instead.
func (*VehicleInput) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{7}
}

func (x *VehicleInput) GetVehicleTypeId() string {
	if x != nil {
		return x.VehicleTypeId
	}
	return ""
}

func (x *VehicleInput) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *VehicleInput) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleInput) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleInput) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *VehicleInput) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *VehicleInput) GetSeatingCapacity() int32 {
	if x != nil {
		return x.SeatingCapacity
	}
	return 0
}

func (x *VehicleInput) GetFuelType() FuelType {
	if x != nil {
		return x.FuelType
	}
	return FuelType_FUEL_UNSPECIFIED
}

func (x *VehicleInput) GetEngineNumber() string {
	if x != nil {
		return x.EngineNumber
	}
	return ""
}

func (x *VehicleInput) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *VehicleInput) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *VehicleInput) GetInsuranceExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.InsuranceExpiry
	}
	return nil
}

type CreateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_vehicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_vehicle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{9}
}

func (x *GetVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_vehicle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{10}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type ListVehiclesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PageSize          int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter      *VehicleStatus         `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=vehicle.VehicleStatus,oneof" json:"status_filter,omitempty"`
	VehicleTypeFilter *string                `protobuf:"bytes,4,opt,name=vehicle_type_filter,json=vehicleTypeFilter,proto3,oneof" json:"vehicle_type_filter,omitempty"`
	MakeFilter        *string                `protobuf:"bytes,5,opt,name=make_filter,json=makeFilter,proto3,oneof" json:"make_filter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_vehicle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{11}
}

func (x *ListVehiclesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVehiclesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListVehiclesRequest) GetStatusFilter() VehicleStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return VehicleStatus_STATUS_UNSPECIFIED
}

func (x *ListVehiclesRequest) GetVehicleTypeFilter() string {
	if x != nil && x.VehicleTypeFilter != nil {
		return *x.VehicleTypeFilter
	}
	return ""
}

func (x *ListVehiclesRequest) GetMakeFilter() string {
	if x != nil && x.MakeFilter != nil {
		return *x.MakeFilter
	}
	return ""
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_vehicle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{12}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListVehiclesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Vehicle       *VehicleInput          `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_vehicle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicle() *VehicleInput {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *UpdateVehicleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_vehicle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_vehicle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehiclesByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleTypeId string                 `protobuf:"bytes,1,opt,name=vehicle_type_id,json=vehicleTypeId,proto3" json:"vehicle_type_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  *VehicleStatus         `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=vehicle.VehicleStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehiclesByTypeRequest) Reset() {
	*x = GetVehiclesByTypeRequest{}
	mi := &file_vehicle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehiclesByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesByTypeRequest) ProtoMessage() {}

func (x *GetVehiclesByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetVehiclesByTypeRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{16}
}

func (x *GetVehiclesByTypeRequest) GetVehicleTypeId() string {
	if x != nil {
		return x.VehicleTypeId
	}
	return ""
}

func (x *GetVehiclesByTypeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetVehiclesByTypeRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetVehiclesByTypeRequest) GetStatusFilter() VehicleStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return VehicleStatus_STATUS_UNSPECIFIED
}

type GetAvailableVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleTypeId *string                `protobuf:"bytes,1,opt,name=vehicle_type_id,json=vehicleTypeId,proto3,oneof" json:"vehicle_type_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVehiclesRequest) Reset() {
	*x = GetAvailableVehiclesRequest{}
	mi := &file_vehicle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVehiclesRequest) ProtoMessage() {}

func (x *GetAvailableVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{17}
}

func (x *GetAvailableVehiclesRequest) GetVehicleTypeId() string {
	if x != nil && x.VehicleTypeId != nil {
		return *x.VehicleTypeId
	}
	return ""
}

func (x *GetAvailableVehiclesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAvailableVehiclesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type UpdateVehicleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=vehicle.VehicleStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleStatusRequest) Reset() {
	*x = UpdateVehicleStatusRequest{}
	mi := &file_vehicle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleStatusRequest) ProtoMessage() {}

func (x *UpdateVehicleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleStatusRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateVehicleStatusRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UpdateVehicleStatusRequest) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_STATUS_UNSPECIFIED
}

type UpdateVehicleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleStatusResponse) Reset() {
	*x = UpdateVehicleStatusResponse{}
	mi := &file_vehicle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleStatusResponse) ProtoMessage() {}

func (x *UpdateVehicleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleStatusResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateVehicleStatusResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

var File_vehicle_proto protoreflect.FileDescriptor

const file_vehicle_proto_rawDesc = "" +
	"\n" +
	"\rvehicle.proto\x12\avehicle\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\x8e\x01\n" +
	"\vVehicleType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x18CreateVehicleTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"T\n" +
	"\x19CreateVehicleTypeResponse\x127\n" +
	"\fvehicle_type\x18\x01 \x01(\v2\x14.vehicle.VehicleTypeR\vvehicleType\"U\n" +
	"\x17ListVehicleTypesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"}\n" +
	"\x18ListVehicleTypesResponse\x129\n" +
	"\rvehicle_types\x18\x01 \x03(\v2\x14.vehicle.VehicleTypeR\fvehicleTypes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd7\x05\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fvehicle_type_id\x18\x02 \x01(\tR\rvehicleTypeId\x12*\n" +
	"\x11vehicle_type_name\x18\x03 \x01(\tR\x0fvehicleTypeName\x12#\n" +
	"\rlicense_plate\x18\x04 \x01(\tR\flicensePlate\x12\x12\n" +
	"\x04make\x18\x05 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\a \x01(\x05R\x04year\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12)\n" +
	"\x10seating_capacity\x18\t \x01(\x05R\x0fseatingCapacity\x12.\n" +
	"\tfuel_type\x18\n" +
	" \x01(\x0e2\x11.vehicle.FuelTypeR\bfuelType\x12#\n" +
	"\rengine_number\x18\v \x01(\tR\fengineNumber\x12%\n" +
	"\x0echassis_number\x18\f \x01(\tR\rchassisNumber\x12G\n" +
	"\x11registration_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\x12E\n" +
	"\x10insurance_expiry\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x0finsuranceExpiry\x12.\n" +
	"\x06status\x18\x0f \x01(\x0e2\x16.vehicle.VehicleStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\r\n" +
	"\v_updated_at\"G\n" +
	"\x14CreateVehicleRequest\x12/\n" +
	"\avehicle\x18\x01 \x01(\v2\x15.vehicle.VehicleInputR\avehicle\"\xe6\x03\n" +
	"\fVehicleInput\x12&\n" +
	"\x0fvehicle_type_id\x18\x01 \x01(\tR\rvehicleTypeId\x12#\n" +
	"\rlicense_plate\x18\x02 \x01(\tR\flicensePlate\x12\x12\n" +
	"\x04make\x18\x03 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12)\n" +
	"\x10seating_capacity\x18\a \x01(\x05R\x0fseatingCapacity\x12.\n" +
	"\tfuel_type\x18\b \x01(\x0e2\x11.vehicle.FuelTypeR\bfuelType\x12#\n" +
	"\rengine_number\x18\t \x01(\tR\fengineNumber\x12%\n" +
	"\x0echassis_number\x18\n" +
	" \x01(\tR\rchassisNumber\x12G\n" +
	"\x11registration_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\x12E\n" +
	"\x10insurance_expiry\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0finsuranceExpiry\"C\n" +
	"\x15CreateVehicleResponse\x12*\n" +
	"\avehicle\x18\x01 \x01(\v2\x10.vehicle.VehicleR\avehicle\"2\n" +
	"\x11GetVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"@\n" +
	"\x12GetVehicleResponse\x12*\n" +
	"\avehicle\x18\x01 \x01(\v2\x10.vehicle.VehicleR\avehicle\"\xa8\x02\n" +
	"\x13ListVehiclesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12@\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x16.vehicle.VehicleStatusH\x00R\fstatusFilter\x88\x01\x01\x123\n" +
	"\x13vehicle_type_filter\x18\x04 \x01(\tH\x01R\x11vehicleTypeFilter\x88\x01\x01\x12$\n" +
	"\vmake_filter\x18\x05 \x01(\tH\x02R\n" +
	"makeFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filterB\x16\n" +
	"\x14_vehicle_type_filterB\x0e\n" +
	"\f_make_filter\"\x8d\x01\n" +
	"\x14ListVehiclesResponse\x12,\n" +
	"\bvehicles\x18\x01 \x03(\v2\x10.vehicle.VehicleR\bvehicles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xa3\x01\n" +
	"\x14UpdateVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12/\n" +
	"\avehicle\x18\x02 \x01(\v2\x15.vehicle.VehicleInputR\avehicle\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"C\n" +
	"\x15UpdateVehicleResponse\x12*\n" +
	"\avehicle\x18\x01 \x01(\v2\x10.vehicle.VehicleR\avehicle\"5\n" +
	"\x14DeleteVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"\xd2\x01\n" +
	"\x18GetVehiclesByTypeRequest\x12&\n" +
	"\x0fvehicle_type_id\x18\x01 \x01(\tR\rvehicleTypeId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12@\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x16.vehicle.VehicleStatusH\x00R\fstatusFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filter\"\x9a\x01\n" +
	"\x1bGetAvailableVehiclesRequest\x12+\n" +
	"\x0fvehicle_type_id\x18\x01 \x01(\tH\x00R\rvehicleTypeId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\x12\n" +
	"\x10_vehicle_type_id\"k\n" +
	"\x1aUpdateVehicleStatusRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.vehicle.VehicleStatusR\x06status\"I\n" +
	"\x1bUpdateVehicleStatusResponse\x12*\n" +
	"\avehicle\x18\x01 \x01(\v2\x10.vehicle.VehicleR\avehicle*_\n" +
	"\rVehicleStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\x0f\n" +
	"\vMAINTENANCE\x10\x02\x12\v\n" +
	"\aRETIRED\x10\x03\x12\f\n" +
	"\bASSIGNED\x10\x04*R\n" +
	"\bFuelType\x12\x14\n" +
	"\x10FUEL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PETROL\x10\x01\x12\n" +
	"\n" +
	"\x06DIESEL\x10\x02\x12\f\n" +
	"\bELECTRIC\x10\x03\x12\n" +
	"\n" +
	"\x06HYBRID\x10\x042\xd7\x06\n" +
	"\x0eVehicleService\x12N\n" +
	"\rCreateVehicle\x12\x1d.vehicle.CreateVehicleRequest\x1a\x1e.vehicle.CreateVehicleResponse\x12E\n" +
	"\n" +
	"GetVehicle\x12\x1a.vehicle.GetVehicleRequest\x1a\x1b.vehicle.GetVehicleResponse\x12K\n" +
	"\fListVehicles\x12\x1c.vehicle.ListVehiclesRequest\x1a\x1d.vehicle.ListVehiclesResponse\x12N\n" +
	"\rUpdateVehicle\x12\x1d.vehicle.UpdateVehicleRequest\x1a\x1e.vehicle.UpdateVehicleResponse\x12F\n" +
	"\rDeleteVehicle\x12\x1d.vehicle.DeleteVehicleRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x11GetVehiclesByType\x12!.vehicle.GetVehiclesByTypeRequest\x1a\x1d.vehicle.ListVehiclesResponse\x12[\n" +
	"\x14GetAvailableVehicles\x12$.vehicle.GetAvailableVehiclesRequest\x1a\x1d.vehicle.ListVehiclesResponse\x12`\n" +
	"\x13UpdateVehicleStatus\x12#.vehicle.UpdateVehicleStatusRequest\x1a$.vehicle.UpdateVehicleStatusResponse\x12Z\n" +
	"\x11CreateVehicleType\x12!.vehicle.CreateVehicleTypeRequest\x1a\".vehicle.CreateVehicleTypeResponse\x12W\n" +
	"\x10ListVehicleTypes\x12 .vehicle.ListVehicleTypesRequest\x1a!.vehicle.ListVehicleTypesResponseB;Z9github.com/adammwaniki/bebabeba/services/vehicle/genprotob\x06proto3"

var (
	file_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_proto_rawDescData []byte
)

func file_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)))
	})
	return file_vehicle_proto_rawDescData
}

var file_vehicle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_vehicle_proto_goTypes = []any{
	(VehicleStatus)(0),                  // 0: vehicle.VehicleStatus
	(FuelType)(0),                       // 1: vehicle.FuelType
	(*VehicleType)(nil),                 // 2: vehicle.VehicleType
	(*CreateVehicleTypeRequest)(nil),    // 3: vehicle.CreateVehicleTypeRequest
	(*CreateVehicleTypeResponse)(nil),   // 4: vehicle.CreateVehicleTypeResponse
	(*ListVehicleTypesRequest)(nil),     // 5: vehicle.ListVehicleTypesRequest
	(*ListVehicleTypesResponse)(nil),    // 6: vehicle.ListVehicleTypesResponse
	(*Vehicle)(nil),                     // 7: vehicle.Vehicle
	(*CreateVehicleRequest)(nil),        // 8: vehicle.CreateVehicleRequest
	(*VehicleInput)(nil),                // 9: vehicle.VehicleInput
	(*CreateVehicleResponse)(nil),       // 10: vehicle.CreateVehicleResponse
	(*GetVehicleRequest)(nil),           // 11: vehicle.GetVehicleRequest
	(*GetVehicleResponse)(nil),          // 12: vehicle.GetVehicleResponse
	(*ListVehiclesRequest)(nil),         // 13: vehicle.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),        // 14: vehicle.ListVehiclesResponse
	(*UpdateVehicleRequest)(nil),        // 15: vehicle.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil),       // 16: vehicle.UpdateVehicleResponse
	(*DeleteVehicleRequest)(nil),        // 17: vehicle.DeleteVehicleRequest
	(*GetVehiclesByTypeRequest)(nil),    // 18: vehicle.GetVehiclesByTypeRequest
	(*GetAvailableVehiclesRequest)(nil), // 19: vehicle.GetAvailableVehiclesRequest
	(*UpdateVehicleStatusRequest)(nil),  // 20: vehicle.UpdateVehicleStatusRequest
	(*UpdateVehicleStatusResponse)(nil), // 21: vehicle.UpdateVehicleStatusResponse
	(*timestamppb.Timestamp)(nil),       // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),       // 23: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),               // 24: google.protobuf.Empty
}
var file_vehicle_proto_depIdxs = []int32{
	22, // 0: vehicle.VehicleType.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: vehicle.CreateVehicleTypeResponse.vehicle_type:type_name -> vehicle.VehicleType
	2,  // 2: vehicle.ListVehicleTypesResponse.vehicle_types:type_name -> vehicle.VehicleType
	1,  // 3: vehicle.Vehicle.fuel_type:type_name -> vehicle.FuelType
	22, // 4: vehicle.Vehicle.registration_date:type_name -> google.protobuf.Timestamp
	22, // 5: vehicle.Vehicle.insurance_expiry:type_name -> google.protobuf.Timestamp
	0,  // 6: vehicle.Vehicle.status:type_name -> vehicle.VehicleStatus
	22, // 7: vehicle.Vehicle.created_at:type_name -> google.protobuf.Timestamp
	22, // 8: vehicle.Vehicle.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 9: vehicle.CreateVehicleRequest.vehicle:type_name -> vehicle.VehicleInput
	1,  // 10: vehicle.VehicleInput.fuel_type:type_name -> vehicle.FuelType
	22, // 11: vehicle.VehicleInput.registration_date:type_name -> google.protobuf.Timestamp
	22, // 12: vehicle.VehicleInput.insurance_expiry:type_name -> google.protobuf.Timestamp
	7,  // 13: vehicle.CreateVehicleResponse.vehicle:type_name -> vehicle.Vehicle
	7,  // 14: vehicle.GetVehicleResponse.vehicle:type_name -> vehicle.Vehicle
	0,  // 15: vehicle.ListVehiclesRequest.status_filter:type_name -> vehicle.VehicleStatus
	7,  // 16: vehicle.ListVehiclesResponse.vehicles:type_name -> vehicle.Vehicle
	9,  // 17: vehicle.UpdateVehicleRequest.vehicle:type_name -> vehicle.VehicleInput
	23, // 18: vehicle.UpdateVehicleRequest.update_mask:type_name -> google.protobuf.FieldMask
	7,  // 19: vehicle.UpdateVehicleResponse.vehicle:type_name -> vehicle.Vehicle
	0,  // 20: vehicle.GetVehiclesByTypeRequest.status_filter:type_name -> vehicle.VehicleStatus
	0,  // 21: vehicle.UpdateVehicleStatusRequest.status:type_name -> vehicle.VehicleStatus
	7,  // 22: vehicle.UpdateVehicleStatusResponse.vehicle:type_name -> vehicle.Vehicle
	8,  // 23: vehicle.VehicleService.CreateVehicle:input_type -> vehicle.CreateVehicleRequest
	11, // 24: vehicle.VehicleService.GetVehicle:input_type -> vehicle.GetVehicleRequest
	13, // 25: vehicle.VehicleService.ListVehicles:input_type -> vehicle.ListVehiclesRequest
	15, // 26: vehicle.VehicleService.UpdateVehicle:input_type -> vehicle.UpdateVehicleRequest
	17, // 27: vehicle.VehicleService.DeleteVehicle:input_type -> vehicle.DeleteVehicleRequest
	18, // 28: vehicle.VehicleService.GetVehiclesByType:input_type -> vehicle.GetVehiclesByTypeRequest
	19, // 29: vehicle.VehicleService.GetAvailableVehicles:input_type -> vehicle.GetAvailableVehiclesRequest
	20, // 30: vehicle.VehicleService.UpdateVehicleStatus:input_type -> vehicle.UpdateVehicleStatusRequest
	3,  // 31: vehicle.VehicleService.CreateVehicleType:input_type -> vehicle.CreateVehicleTypeRequest
	5,  // 32: vehicle.VehicleService.ListVehicleTypes:input_type -> vehicle.ListVehicleTypesRequest
	10, // 33: vehicle.VehicleService.CreateVehicle:output_type -> vehicle.CreateVehicleResponse
	12, // 34: vehicle.VehicleService.GetVehicle:output_type -> vehicle.GetVehicleResponse
	14, // 35: vehicle.VehicleService.ListVehicles:output_type -> vehicle.ListVehiclesResponse
	16, // 36: vehicle.VehicleService.UpdateVehicle:output_type -> vehicle.UpdateVehicleResponse
	24, // 37: vehicle.VehicleService.DeleteVehicle:output_type -> google.protobuf.Empty
	14, // 38: vehicle.VehicleService.GetVehiclesByType:output_type -> vehicle.ListVehiclesResponse
	14, // 39: vehicle.VehicleService.GetAvailableVehicles:output_type -> vehicle.ListVehiclesResponse
	21, // 40: vehicle.VehicleService.UpdateVehicleStatus:output_type -> vehicle.UpdateVehicleStatusResponse
	4,  // 41: vehicle.VehicleService.CreateVehicleType:output_type -> vehicle.CreateVehicleTypeResponse
	6,  // 42: vehicle.VehicleService.ListVehicleTypes:output_type -> vehicle.ListVehicleTypesResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_vehicle_proto_init() }
func file_vehicle_proto_init() {
	if File_vehicle_proto != nil {
		return
	}
	file_vehicle_proto_msgTypes[5].OneofWrappers = []any{}
	file_vehicle_proto_msgTypes[11].OneofWrappers = []any{}
	file_vehicle_proto_msgTypes[16].OneofWrappers = []any{}
	file_vehicle_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_proto_depIdxs,
		EnumInfos:         file_vehicle_proto_enumTypes,
		MessageInfos:      file_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_proto = out.File
	file_vehicle_proto_goTypes = nil
	file_vehicle_proto_depIdxs = nil
}
